---
- name: Include variables
  include_vars: main.yml

- name: Download Bloomberg Terminal
  win_get_url:
    url: https://bdn-ak-ssl.bloomberg.com/software/trv/sotrt05072020.exe
    dest: 'C:\Scripts\sotrt05072020.exe'

- name: Install Bloomberg Terminal
  raw: 'C:\Scripts\sotrt05072020.exe /Quiet /NoRestart /Full'
...